# Generated by Django 5.1.1 on 2024-09-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanagement', '0002_user_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isBorrowed',
            field=models.BooleanField(default=False),
        ),
    ]
