# Generated by Django 5.1.1 on 2024-09-12 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanagement', '0006_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrow_duration',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
