# Generated by Django 5.1.1 on 2024-09-12 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanagement', '0007_book_borrow_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='borrow_duration',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
