# Generated by Django 5.1.1 on 2024-09-12 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanagement', '0008_alter_book_borrow_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalouge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='bookmanagement.book')),
            ],
        ),
    ]
