# Generated by Django 5.1.1 on 2024-09-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanagement', '0009_catalouge'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available',
            field=models.DateField(blank=True, null=True),
        ),
    ]
